name: Deploy to Amazon ECS

on:
  workflow_run:
    workflows: [ cv-as-service image build ] 
    types: 
      - completed
  push:
    branches:
      - main
    paths:
      - '.aws/taskdef.json'
      - 'main.tf'
      - '.github/workflows/aws.yml'
      
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: .aws/taskdef.json
        container-name: cv-as-service
        image: public.ecr.aws/g6k1i6y8/cv-as-service:latest

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: cv-as-service
        cluster: cv-as-service-iaac
        wait-for-service-stability: true
        force-new-deployment: true
