name: Deploy infrastructure to AWS

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy
      working-directory: infrastructure
      run: |
        npm ci
        npx cdk deploy --ci --require-approval never
        
