name: cv-builder image build

on:
  push:
    branches: [ main ]
    paths: 
      - 'cv-builder/*' 
      - '.github/workflows/cv-builder-image.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to ECR, Build, tag and push 
      run: |
        cd cv-builder/
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws  
        docker build -t cv-builder:latest .
        docker tag cv-builder:latest public.ecr.aws/g6k1i6y8/cv-builder:latest
        docker push public.ecr.aws/g6k1i6y8/cv-builder:latest