name: cv-builder image build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: cv-builder/Dockerfile
  pull_request:
    branches: [ main ]
    paths: cv-builder/Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd cv-builder && docker build . --tag cv-builder
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        local-image: cv-builder
        image: cv-builder, cv-builder:latest
